hmcts/fact-admin

package.json
src/main/modules/passport/index.ts
src/main/views/courts.njk
src/main/views/home.njk
src/main/views/logout.njk
src/main/views/template.njk
src/test/a11y/a11y.ts
src/test/config.ts
src/test/functional/features/homepage.feature
src/test/functional/features/login.feature
src/test/functional/features/logout.feature
src/test/functional/steps/homepage.ts
src/test/functional/steps/login.ts
src/test/functional/steps/logout.ts
src/test/functional/support/hooks.ts
src/test/functional/utlis/puppeteer.util.ts
src/test/unit/app/controller/CourtsController.ts
src/test/unit/app/controller/HomeController.ts
yarn.lock

Fact 77/78 login logout clean up

---

src/main/app/auth/AuthProviderFactory.ts
src/main/modules/awilix/index.ts
src/main/modules/passport/index.ts
src/main/types/AuthedRequest.ts
src/test/unit/app/controller/CourtsController.ts

Add auth to API calls

---

charts/fact-admin/Chart.yaml
charts/fact-admin/values.yaml
config/custom-environment-variables.yaml
config/default.yaml
package.json
src/main/modules/appinsights/index.ts
src/main/modules/properties-volume/index.ts
src/main/server.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-120
Enable appinsights

Add application insights

---

package.json
src/main/app/controller/courts/CourtDetailsController.ts
src/main/app/controller/courts/EditCourtController.ts
src/main/modules/awilix/index.ts
src/main/routes.ts
src/main/views/courts/court-details.njk
src/main/views/courts/courts.njk
src/main/views/courts/edit-court.njk
src/main/views/webpack/js.njk
src/test/a11y/a11y.ts
src/test/functional/features/courts.feature
src/test/functional/steps/courts.ts
src/test/unit/app/controller/courts/EditCourtController.ts

https://tools.hmcts.net/jira/browse/FACT-63
Edit court / tribunal
```
[ ] Yes
[ x] No
```

Fact 63 edit court tribunal

---

jest.a11y.config.js
jest.timeout.config.js
package.json
src/main/views/courts/edit-court-general.njk
src/main/views/webpack/js.njk

https://tools.hmcts.net/jira/browse/FACT-210
Fix "view in new window" link on the edit page, now displays view of court.
```
[ ] Yes
[x] No
```

Fact 210 fix link on edit page

---

src/main/app/controller/courts/EditCourtGeneralController.ts
src/main/views/courts/edit-court-general.njk
src/test/functional/features/court-open-and-access-scheme.feature
src/test/functional/steps/court-urgent.ts
src/test/unit/app/controller/courts/EditCourtGeneralController.ts

JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/FACT-93
Change description
Admin Journey - closed courts and access scheme flags

Fact 93 general checkboxes

---

src/test/a11y/a11y.ts

Add general edit tab to Pa11y tests
```
[ ] Yes
[x] No
```

Add general tab pa11y test

---

src/main/app/controller/courts/EditCourtGeneralController.ts
src/main/views/bulk-update/index.njk
src/main/views/courts/courts.njk
src/main/views/courts/edit-court-general.njk
src/main/views/courts/tabs/general.njk
src/main/views/courts/tabs/openingHours.njk
src/test/functional/steps/court-urgent.ts
src/test/unit/app/controller/courts/EditCourtGeneralController.ts

https://tools.hmcts.net/jira/browse/FACT-73
Opening hours
```
[ ] Yes
[ ] No
```

Fact 73 opening time

---

src/main/views/courts/tabs/general.njk

FACT-93: update help text

---

charts/fact-admin/Chart.yaml
charts/fact-admin/values.aat.template.yaml

remove idampr for aat stop neuvector errors

---

config/default.yaml
src/main/modules/properties-volume/index.ts

change the way vault secrets are loaded

---

api/fact-api-stubs.ts
src/main/app/controller/courts/CourtsDownloadController.ts
src/test/unit/app/fact/FactApi.ts

https://tools.hmcts.net/jira/browse/FACT-166
Add additional fields

FACT-166: Add ational fields for download

---

charts/fact-admin/Chart.yaml
charts/fact-admin/values.aat.template.yaml
charts/fact-admin/values.preview.template.yaml
charts/fact-admin/values.yaml

Fix FRONTEND_URL

---

src/main/app/controller/courts/CourtsDownloadController.ts

https://tools.hmcts.net/jira/browse/FACT-166
fix filename

Fix filename

---

src/main/app/controller/courts/CourtsDownloadController.ts

https://tools.hmcts.net/jira/browse/FACT-166
Separate DX code from contacts

FACT-166 separate DX

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/FACT-288
sync branches with master

FACT-288: sync branches with master

---

api/fact-api-stubs.ts
charts/fact-admin/Chart.yaml
src/main/app/controller/courts/EditCourtGeneralController.ts
src/main/app/controller/courts/OpeningTimesController.ts
src/main/app/fact/FactApi.ts
src/main/assets/js/index.ts
src/main/assets/js/opening-hours.ts
src/main/modules/awilix/index.ts
src/main/modules/nunjucks/index.ts
src/main/routes.ts
src/main/server.ts
src/main/types/Court.ts
src/main/types/CourtPageData.ts
src/main/types/OpeningTime.ts
src/main/types/OpeningType.ts
src/main/views/courts/edit-court-general.njk
src/main/views/courts/tabs/openingHours.njk
src/main/views/courts/tabs/openingHoursContent.njk
src/test/functional/features/court-additional-information.feature
src/test/functional/features/court-open-and-access-scheme.feature
src/test/functional/features/court-urgent.feature
src/test/functional/features/opening-hours.feature
src/test/functional/steps/opening-hours.ts
src/test/functional/utlis/puppeteer.util.ts
src/test/unit/app/controller/courts/EditCourtGeneralController.ts
src/test/unit/app/controller/courts/OpeningTimesController.ts
src/test/unit/app/fact/FactApi.ts

https://tools.hmcts.net/jira/browse/FACT-407
Changes to opening time tab to make it a separate form that gets and posts its data via ajax. The save functionality for the general tab is removed until the same changes are made to that tab.
```
[ ] Yes
[x] No
```

FACT-407 Changes to opening time tab to make it a separate form that gets and posts its data via ajax. 

---

src/main/app/controller/courts/ContactsController.ts
src/main/app/fact/FactApi.ts
src/main/assets/js/ajaxErrorHandler.ts
src/main/assets/js/courtGeneralInfo.ts
src/main/assets/js/emails.ts
src/main/assets/js/index.ts
src/main/assets/js/opening-hours.ts
src/main/assets/js/phone-numbers.ts
src/main/modules/awilix/index.ts
src/main/modules/oidc/index.ts
src/main/routes.ts
src/main/types/Contact.ts
src/main/types/ContactType.ts
src/main/views/courts/edit-court-general.njk
src/main/views/courts/tabs/phoneNumbers.njk
src/main/views/courts/tabs/phoneNumbersContent.njk
src/test/functional/features/phone-numbers.feature
src/test/functional/steps/opening-hours.ts
src/test/functional/steps/phone-numbers.ts
src/test/functional/utlis/helpers.ts
src/test/unit/app/controller/courts/ContactsController.ts
src/test/unit/app/fact/FactApi.ts

https://tools.hmcts.net/jira/browse/FACT-74
https://tools.hmcts.net/jira/browse/FACT-477
- Added new phone numbers tab that gets and posts its data via ajax including unit and functional tests.
- Added new ajax error handler and updated existing tab front-end scripts to use this.
- Updated OIDC middleware to allow redirects due to session expiry to be done in the ajax error handler.
```
[ ] Yes
[x] No
```

FACT-477 Added new phone numbers tab that gets and posts its data via ajax

---

config/custom-environment-variables.yaml
config/default.yaml
infrastructure/main.tf

CSRF-Token-Patch

---

config/default.yaml
src/main/modules/properties-volume/index.ts

CSRF-Token-Patch - Potential fix 2

---

Jenkinsfile_CNP
README.md
src/test/functional/features/admin-login.feature
src/test/functional/features/bulk-update.feature
src/test/functional/features/court-additional-information.feature
src/test/functional/features/court-open-and-access-scheme.feature
src/test/functional/features/court-urgent.feature
src/test/functional/features/courts.feature
src/test/functional/features/email-addresses.feature
src/test/functional/features/general-info.feature
src/test/functional/features/opening-hours.feature
src/test/functional/features/phone-numbers.feature
src/test/functional/puppeteer.config.ts
src/test/functional/steps/courts.ts
src/test/functional/steps/login.ts
src/test/functional/support/hooks.ts
src/test/functional/utlis/puppeteer.util.ts

https://tools.hmcts.net/jira/browse/FACT-514
Removed the test log-in credentials from all functional tests and the readme file.
```
[ ] Yes
[x] No
```

FACT-514 Removed test log-in credentials from functional tests and readme file.

---

src/main/app/controller/courts/CourtTypesController.ts
src/main/views/courts/tabs/typesContent.njk

https://tools.hmcts.net/jira/browse/FACT-70
Amended validation messages and heading for more clarity. in response to issue raised by QA
```
[ ] Yes
[ x] No
```

Amended validation messages and heading for more clarity.

---

src/main/modules/nunjucks/index.ts
src/main/views/courts/edit-court-general.njk

https://tools.hmcts.net/jira/browse/FACT-563
- Utilised FACT-FRONTEND-URL variable (set based on ENV) to be included within Nunjucks.
- Appended FACT-FRONTEND-URL onto beginning of 'view in new window' link on court editing pages.
- Updated 'view in new window' copy to be 'View court in new tab'.
```
[ ] Yes
[x] No
```

FACT-563 - Fixed issue with 'View in new window' not opening pages correctly.

---

src/main/assets/js/emails.ts
src/main/views/courts/tabs/emailsContent.njk
src/test/functional/features/email-addresses.feature
src/test/functional/steps/email-addresses.ts

https://tools.hmcts.net/jira/browse/FACT-293
Added ability to re-order email addresses for a court in the admin portal.
```
[ ] Yes
[x] No
```

FACT-293 Add ability to re-order email addresses

---

src/test/functional/steps/login.ts
src/test/functional/utlis/puppeteer.util.ts

https://tools.hmcts.net/jira/browse/FACT-541
Functional tests for login changed. Changed textbox typing to setting a value.
```
[ ] Yes
[x] No
```

FACT-541 - Login functional test changes

---

cucumber.js
src/test/functional/features/opening-hours.feature
src/test/functional/features/phone-numbers.feature
src/test/functional/steps/opening-hours.ts
src/test/functional/steps/phone-numbers.ts

Missing steps are added for the functional tests
```
[ ] Yes
[ ] No
```

Fact 291 1

---

src/main/assets/js/phone-numbers.ts
src/main/assets/js/utilities.ts
src/main/views/courts/tabs/phoneNumbersContent.njk
src/test/functional/features/phone-numbers.feature
src/test/functional/steps/phone-numbers.ts

https://tools.hmcts.net/jira/browse/FACT-291
Add ability to re-order phone numbers
```
[ ] Yes
[x] No
```

FACT-291 Add ability to re-order phone numbers.

---

src/test/functional/utlis/puppeteer.util.ts

setElementValueForInputField method changed
```
[ ] Yes
[x] No
```

setElementValueForInputField method changed

---

src/test/functional/steps/court-types.ts
src/test/functional/steps/email-addresses.ts
src/test/functional/steps/opening-hours.ts
src/test/functional/steps/phone-numbers.ts

https://tools.hmcts.net/jira/browse/FACT-609
Refactored functional tests to improve performance.
```
[ ] Yes
[x] No
```

Refactored functional tests for performance improvements

---

src/main/assets/js/fact-tabs/fact-tabs-index.js
src/main/assets/js/fact-tabs/fact-tabs.js
src/main/assets/js/index.ts
src/main/assets/scss/main.scss
src/main/assets/scss/scrollbar.scss
src/main/assets/scss/tabs.scss
src/main/views/courts/edit-court-general.njk
src/main/views/courts/tabs/localAuthoritiesContent.njk
src/main/views/macros/tabs/macro.njk
src/main/views/macros/tabs/template.njk
src/test/functional/features/court-types.feature
src/test/functional/features/email-addresses.feature
src/test/functional/features/general-info.feature
src/test/functional/features/local-authorities.feature
src/test/functional/features/opening-hours.feature
src/test/functional/features/phone-numbers.feature
src/test/functional/steps/court-types.ts
src/test/functional/steps/email-addresses.ts
src/test/functional/steps/general-info.ts
src/test/functional/steps/local-authorities.ts
src/test/functional/steps/opening-hours.ts
src/test/functional/steps/phone-numbers.ts
src/test/functional/utlis/puppeteer.util.ts

https://tools.hmcts.net/jira/browse/FACT-652
```
[ ] Yes
[x] No
```

FACT-652 adding bespoke tabs component

---

src/main/app/controller/courts/CourtsDownloadController.ts

https://tools.hmcts.net/jira/browse/FACT-700
Show application update column in court download
```
[ ] Yes
[x] No
```

FACT-700 - Show application update column in court download

---

src/main/app/controller/courts/CourtsDownloadController.ts
src/main/app/controller/lists/ListsController.ts
src/main/modules/awilix/index.ts
src/main/routes.ts
src/main/views/lists/index.njk
src/main/views/lists/tabs/localAuthorities.njk
src/main/views/template.njk
src/test/unit/app/controller/lists/ListsController.ts

https://tools.hmcts.net/jira/browse/FACT-676
Add lists page to admin portal
```
[ ] Yes
[x] No
```

FACT-676 - Add lists page to admin portal

---

src/main/views/template.njk

https://tools.hmcts.net/jira/browse/FACT-676
Add spacing between links on admin portal heading
```
[ ] Yes
[x] No
```

FACT-676 - Add spacing between links on admin portal heading

---

src/test/functional/features/court-additional-information.feature
src/test/functional/features/court-open-and-access-scheme.feature
src/test/functional/features/court-urgent.feature
src/test/functional/features/email-addresses.feature
src/test/functional/features/general-info.feature
src/test/functional/features/opening-hours.feature
src/test/functional/features/phone-numbers.feature
src/test/functional/steps/court-urgent.ts
src/test/functional/steps/general-info.ts

FACT-774 - Fact court open and access scheme and related changes
https://tools.hmcts.net/jira/browse/FACT-774
Functiona tests for fact court open and access scheme and related changes
```
[ ] Yes
[x] No
```

FACT-774 - Fact court open and access scheme and related changes

---

src/main/app/controller/courts/PostcodesController.ts
src/main/assets/js/court-types.ts
src/main/assets/js/postcodes.ts
src/main/views/courts/tabs/postcodesContent.njk
src/test/functional/features/postcodes.feature
src/test/unit/app/controller/courts/PostcodeController.ts

Fact 100 fixes

---

charts/fact-admin/Chart.yaml

- Upgraded nodejs helm-chart version to 2.3.7
```
[ ] Yes
[x] No
```

helm-chart-upgrade - Upgraded helm charts

---

package.json
src/test/functional/steps/courts.ts
src/test/functional/steps/opening-hours.ts
src/test/functional/steps/phone-numbers.ts

https://tools.hmcts.net/jira/browse/FACT-609
Updated cucumber test command line to include parallel running.
```
[ ] Yes
[x] No
```

Run cucumber tests in parallel

---

src/test/functional/features/court-types.feature
src/test/functional/features/email-addresses.feature

https://tools.hmcts.net/jira/browse/FACT-609
Amended email and court types functional tests to remove dependency between tests. 
```
[ ] Yes
[x] No
```

Amended email and court types functional tests to remove dependency between tests

---

package.json

Upgrade version of url-parse to fix security vulnerability

---

sonar-project.properties

sonarqube file changes

---

src/main/app/controller/courts/AdditionalLinksController.ts
src/main/app/fact/FactApi.ts
src/main/assets/js/additionalLinks.ts
src/main/assets/js/index.ts
src/main/modules/awilix/index.ts
src/main/routes.ts
src/main/types/AdditionalLink.ts
src/main/types/Element.ts
src/main/types/Email.ts
src/main/utils/validation.ts
src/main/views/courts/edit-court-general.njk
src/main/views/courts/tabs/additionalLinks.njk
src/main/views/courts/tabs/additionalLinksContent.njk
src/test/functional/features/additional-links.feature
src/test/functional/steps/additional-links.ts
src/test/functional/steps/postcodes.ts
src/test/unit/app/controller/courts/AdditionalLinksController.ts
src/test/unit/app/fact/FactApi.ts
src/test/unit/app/utils/validation.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-759
Add court additional links tab to admin portal
```
[ ] Yes
[x] No
```

FACT-759 - Add court additional links tab to admin portal

---

src/test/functional/features/admin-logout.feature

test fixes

---

src/main/app/controller/lists/FacilityTypesController.ts
src/main/app/fact/FactApi.ts
src/main/assets/js/facility-types-list.ts
src/main/assets/js/index.ts
src/main/modules/awilix/index.ts
src/main/routes.ts
src/main/types/Facility.ts
src/main/views/lists/index.njk
src/main/views/lists/tabs/deleteFacilityTypeConfirm.njk
src/main/views/lists/tabs/editFacilityType.njk
src/main/views/lists/tabs/facilityTypes.njk
src/main/views/lists/tabs/facilityTypesContent.njk
src/test/functional/features/list-facility-types.feature
src/test/functional/steps/list-facility-types.ts
src/test/functional/utlis/helpers.ts
src/test/unit/app/controller/lists/FacilityTypesController.ts
src/test/unit/app/fact/FactApi.ts

https://tools.hmcts.net/jira/browse/FACT-167
Add new facilities list tab, allowing create, read, update, delete and re-order operations on Facility Types.
```
[ ] Yes
[x] No
```

FACT-167 Add new facility types list tab

---

charts/fact-admin/Chart.yaml
src/main/app/controller/lists/OpeningTypesController.ts
src/main/app/fact/FactApi.ts
src/main/assets/js/index.ts
src/main/assets/js/opening-types-list.ts
src/main/modules/awilix/index.ts
src/main/routes.ts
src/main/views/lists/index.njk
src/main/views/lists/tabs/openingTypes/deleteOpeningTypeConfirm.njk
src/main/views/lists/tabs/openingTypes/editOpeningType.njk
src/main/views/lists/tabs/openingTypes/openingTypes.njk
src/main/views/lists/tabs/openingTypes/openingTypesContent.njk
src/test/functional/features/list-contact-types.feature
src/test/functional/features/list-opening-types.feature
src/test/functional/steps/list-opening-types.ts
src/test/functional/utlis/puppeteer.util.ts
src/test/unit/app/controller/lists/OpeningTypesController.ts
src/test/unit/app/fact/FactApi.ts

https://tools.hmcts.net/jira/browse/FACT-911
adding opening types list
```
[ ] Yes
[x ] No
```

Fact 911 opening types

---

README.md
package.json
src/main/app/controller/courts/GeneralInfoController.ts
src/main/assets/js/courtGeneralInfo.ts
src/main/routes.ts
src/main/types/CourtGeneralInfo.ts
src/main/types/CourtGeneralInfoRedirect.ts
src/main/views/courts/tabs/generalContent.njk
src/main/views/courts/tabs/generalRedirect.njk
src/test/functional/features/court-additional-information.feature
src/test/functional/features/court-open-and-access-scheme.feature
src/test/functional/features/court-urgent.feature
src/test/functional/features/general-info.feature
src/test/functional/steps/general-info.ts
src/test/unit/app/controller/courts/GeneralInfoController.ts
src/test/unit/app/fact/FactApi.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-873
Adding functionality to update court name in general info tab
```
[ ] Yes
[x] No
```

Fact 873 2

---

LICENSE
package.json
src/test/unit/app/utils/FeatureToggleService.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-1053
Addressing vulnerable dependencies identified by ithc testing
```
[ ] Yes
[X] No
```

addressing vulnerable dependencies identified by ithc testing

---

package.json
src/main/assets/js/courtGeneralInfo.ts
src/main/assets/js/facilities.ts
src/main/assets/js/tinymce.config.ts
src/main/assets/js/utilities.ts
src/test/functional/features/facilities.feature
src/test/functional/steps/facilities.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-980
enabling links to be pasted and cleaning up duplicated code
```
[ ] Yes
[x] No
```

FACT-980: enabling links to be pasted and cleaning up duplicated code

---

package.json
src/main/views/courts/tabs/generalContent.njk
yarn.lock

changing text on page around puas

---

src/main/app/controller/courts/GeneralInfoController.ts
src/main/app/controller/courts/NewCourtController.ts

https://tools.hmcts.net/jira/browse/FACT-1115
Updating court names and adding new courts - removing commas from invalid characters
```
[ ] Yes
[ X] No
```

FACT-1115 

---

package.json
src/main/views/courts/edit-court-general.njk
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-861
correcting SPoE tab name 
```
[ ] Yes
[x ] No
```

correcting SPoE tab name

---

charts/fact-admin/values.aat.template.yaml
charts/fact-admin/values.preview.template.yaml

- Updated idam-pr label to be consistent with labelling of fact-admin service in IDAM 
```
[ ] Yes
[x] No
```

FACT-1137 - Changed 'FACT Admin' to 'fact_admin' for idam-pr label

---

package.json

addressing vulnerabilities on fact-admin in falling nightly build
```
[ ] Yes
[ ] No
```

addressing vulnerabilities

---

src/main/app/controller/courts/GeneralInfoController.ts
src/main/views/courts/tabs/generalContent.njk
src/test/unit/app/controller/courts/GeneralInfoController.ts

https://tools.hmcts.net/jira/browse/FACT-1153
Increasing intro character count to 400
```
[ ] Yes
[x] No
```

FACT-1153: Increasing intro character count to 400

---

src/main/app/controller/courts/GeneralInfoController.ts
src/test/unit/app/controller/courts/GeneralInfoController.ts

https://tools.hmcts.net/jira/browse/FACT-1153
Increasing char limited to account for html tags
```
[ ] Yes
[x] No
```

FACT-1153: Increasing char limited to account for html tags

---

src/main/views/courts/tabs/generalContent.njk
src/test/functional/features/general-info.feature
src/test/functional/steps/general-info.ts

https://tools.hmcts.net/jira/browse/FACT-1041
Amending PUAS flag access level
```
[ ] Yes
[x] No
```

FACT-1141: Amending PUAS flag access level

---

src/main/app/controller/courts/CourtFacilitiesController.ts

https://tools.hmcts.net/jira/browse/FACT-1175
-Fixing bug when comparing facility ids
```
[ ] Yes
[x] No
```

FACT-1175: Fixing bug when comparing facility ids

---

src/test/functional/features/admin-create-user.feature
src/test/functional/steps/admin-create-user.ts

fixing functional test

---

package.json
src/main/routes.ts
src/test/a11y/a11y.ts
yarn.lock

[FACT-1067](https://tools.hmcts.net/jira/browse/FACT-1067)

adding missing pages for pa11y

---

src/main/app/controller/courts/GeneralInfoController.ts
src/main/types/CourtGeneralInfo.ts
src/main/views/courts/tabs/generalContent.njk
src/test/functional/features/general-info.feature
src/test/functional/steps/general-info.ts
src/test/unit/app/controller/courts/ApplicationProgressionController.ts
src/test/unit/app/controller/courts/GeneralInfoController.ts
src/test/unit/app/fact/FactApi.ts

https://tools.hmcts.net/jira/browse/FACT-1007
adding common flag
```
[ ] Yes
[x] No
```

adding common flag

---

src/test/functional/features/facilities.feature
src/test/functional/steps/facilities.ts

https://tools.hmcts.net/jira/browse/FACT-1226
```
[ ] Yes
[x] No
```

Modifying facilities tests

---

src/test/functional/features/admin-audit.feature
src/test/functional/steps/admin-audit.ts

updating audit tests

---

src/main/app/controller/courts/CourtsController.ts
src/main/modules/oidc/index.ts
src/main/server.ts
src/main/views/redirect.njk

Fact remove redirect

---

jest.timeout.config.js
src/main/modules/oidc/index.ts
src/main/views/logout.njk
src/test/a11y/a11y.ts
src/test/functional/steps/logout.ts

saving session

---

src/main/app/controller/courts/CourtsController.ts
src/main/views/courts/courts.njk
src/test/unit/app/controller/courts/CourtsController.ts

https://tools.hmcts.net/jira/browse/FACT-962
Courts page error message
```
[ ] Yes
[X ] No
```

courts page error message

---

src/main/views/courts/edit-court-general.njk

https://tools.hmcts.net/jira/browse/FACT-958
links not appearing on edit court pages
```
[ ] Yes
[X ] No
```

links not appearing

---

src/main/app/controller/audits/AuditController.ts
src/main/routes.ts
src/main/views/audits/auditContent.njk
src/test/unit/app/controller/audits/AuditController.ts

https://tools.hmcts.net/jira/browse/FACT-975
adding audits download.
```
[ ] Yes
[x] No
```

adding audits download

---

src/main/assets/js/audits.ts

updating audit code for vuln

---

package.json
src/main/assets/js/cookie-manager.ts
src/main/assets/js/index.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-1173
adding cookie manager to resolve demo environment refresh issues
```
[ ] Yes
[x ] No
```

adding cookie manager

---

src/main/assets/js/cookie-manager.ts

https://tools.hmcts.net/jira/browse/FACT-1173
```
[ ] Yes
x] No
```

updating cookie manager

---

src/main/app/controller/courts/AddressController.ts
src/main/app/controller/courts/PostcodesController.ts
src/test/unit/app/controller/courts/AddressController.ts
src/test/unit/app/controller/courts/PostcodeController.ts

https://tools.hmcts.net/jira/browse/FACT-1178
fact admin side to grab error by data.message
```
[ ] Yes
[ x ] No
```

FACT-1178 fixed postcodes toString issue on fact admin side

---

Jenkinsfile_CNP
cucumber.js
src/main/app/controller/courts/LocalAuthoritiesController.ts
src/main/app/controller/courts/PostcodesController.ts
src/main/modules/oidc/index.ts
src/main/views/courts/courts.njk
src/main/views/courts/edit-court-general.njk
src/main/views/courts/tabs/localAuthoritiesContent.njk
src/main/views/courts/tabs/postcodesContent.njk
src/test/config.ts
src/test/functional/features/super_admin/admin-audit.feature
src/test/functional/features/viewer/viewer-login.feature
src/test/functional/puppeteer.config.ts
src/test/functional/steps/login.ts
src/test/functional/steps/tabs.ts
src/test/functional/support/hooks.ts

adding fact viewer changes for admin portal

---

src/main/app/controller/courts/AddressController.ts
src/test/functional/features/super_admin/admin-court-addresses.feature
src/test/unit/app/controller/courts/AddressController.ts

https://tools.hmcts.net/jira/browse/FACT-1238
adding duplicate address validation
```
[ ] Yes
[x] No
```

adding duplicate address validation

---

src/main/app/controller/courts/AddressController.ts
src/main/app/controller/courts/GeneralInfoController.ts
src/main/utils/validation.ts
src/test/unit/app/utils/validation.ts

https://tools.hmcts.net/jira/browse/FACT-1192
added removing of spaces from address feilds and general info page
shared function will iterate through data object passed into it and remove all double spaces automatically.
```
[ ] Yes
[ x ] No
```

FACT-1192 adding shared function to remove too many spaces from feilds

---

src/main/app/controller/courts/AdditionalLinksController.ts
src/main/app/controller/courts/AddressController.ts
src/main/app/controller/courts/CasesHeardController.ts
src/main/app/controller/courts/ContactsController.ts
src/main/app/controller/courts/CourtFacilitiesController.ts
src/main/app/controller/courts/CourtSpoeController.ts
src/main/app/controller/courts/CourtTypesController.ts
src/main/app/controller/courts/EmailsController.ts
src/main/app/controller/courts/GeneralInfoController.ts
src/main/app/controller/courts/LocalAuthoritiesController.ts
src/main/app/controller/courts/OpeningTimesController.ts
src/main/app/controller/courts/PhotoController.ts
src/main/app/controller/courts/PostcodesController.ts
src/main/app/feature-flags/FeatureFlags.ts

https://tools.hmcts.net/jira/browse/FACT-1080
remove code smells
```
[ ] Yes
[x] No
```

remove code smells

---

charts/fact-admin/Chart.yaml
package.json
src/main/app/controller/courts/AddressController.ts
src/main/assets/js/addresses.ts
src/main/types/CourtAddress.ts
src/main/types/CourtAddressPageData.ts
src/main/views/courts/tabs/addressesContent.njk
src/test/config.ts
src/test/functional/features/super_admin/admin-court-addresses.feature
src/test/functional/steps/court-addresses.ts
src/test/unit/app/controller/courts/AddressController.ts
src/test/unit/app/fact/FactApi.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-1204
adding secondary address ordering
```
[ ] Yes
[x] No
```

adding secondary address ordering

---

src/main/app/controller/courts/AddressController.ts

https://tools.hmcts.net/jira/browse/FACT-1200
adding visit address to first index
```
[ ] Yes
[x] No
```

adding visit address to first index

---

charts/fact-admin/Chart.yaml
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-1200
update chart version to 2.4.11
```
[ ] Yes
[x] No
```

update chart version to 2.4.11

---

src/main/app/controller/courts/EditCourtController.ts
src/test/functional/features/super_admin/court-lock.feature
src/test/unit/app/controller/courts/EditCourtController.ts
tsconfig.json

https://tools.hmcts.net/jira/browse/FACT-1281
fix error message court name format
```
[ ] Yes
[x] No
```

fix error message court name format

---

src/main/app/controller/courts/AdditionalLinksController.ts
src/main/app/controller/courts/AddressController.ts
src/main/app/controller/courts/ApplicationProgressionController.ts
src/main/app/controller/courts/CasesHeardController.ts
src/main/app/controller/courts/ContactsController.ts
src/main/app/controller/courts/CourtFacilitiesController.ts
src/main/app/controller/courts/CourtSpoeController.ts
src/main/app/controller/courts/CourtTypesController.ts
src/main/app/controller/courts/EditCourtController.ts
src/main/app/controller/courts/EmailsController.ts
src/main/app/controller/courts/GeneralInfoController.ts
src/main/app/controller/courts/LocalAuthoritiesController.ts
src/main/app/controller/courts/NewCourtController.ts
src/main/app/controller/courts/OpeningTimesController.ts
src/main/app/controller/courts/PhotoController.ts
src/main/app/controller/courts/PostcodesController.ts
src/main/app/controller/lists/AreasOfLawController.ts
src/main/app/controller/lists/ContactTypesController.ts
src/main/app/controller/lists/FacilityTypesController.ts
src/main/app/controller/lists/LocalAuthoritiesListController.ts
src/main/app/controller/lists/OpeningTypesController.ts
src/main/app/controller/users/UserController.ts

https://tools.hmcts.net/jira/browse/FACT-1265
add doc string to main controller methods
```
[ ] Yes
[x] No
```

add doc string to main controller methods

---

src/main/assets/js/additionalLinks.ts
src/main/assets/js/addresses.ts
src/main/assets/js/application-progression.ts
src/main/assets/js/cases-heard.ts
src/main/assets/js/court-types.ts
src/main/assets/js/courtGeneralInfo.ts
src/main/assets/js/emails.ts
src/main/assets/js/facilities.ts
src/main/assets/js/local-authorities.ts
src/main/assets/js/opening-hours.ts
src/main/assets/js/phone-numbers.ts
src/main/assets/js/photo.ts
src/main/assets/js/postcodes.ts
src/main/assets/js/spoe.ts
src/main/assets/js/tab-reset.ts

https://tools.hmcts.net/jira/browse/FACT-1208
added removal of green success banner when switching around tabs
```
[ ] Yes
[ ] No
```

FACT-1208 added code to reset success banner on all tabs

---

src/test/functional/steps/login.ts

functional test amendment

---

src/main/app/controller/courts/AdditionalLinksController.ts
src/main/app/controller/courts/ApplicationProgressionController.ts
src/main/app/controller/courts/ContactsController.ts
src/main/app/controller/courts/CourtFacilitiesController.ts
src/main/app/controller/courts/CourtTypesController.ts
src/main/app/controller/courts/EmailsController.ts
src/main/app/controller/courts/GeneralInfoController.ts
src/main/app/controller/courts/OpeningTimesController.ts
src/main/app/controller/lists/AreasOfLawController.ts
src/main/app/controller/lists/ContactTypesController.ts
src/main/app/controller/lists/FacilityTypesController.ts
src/main/app/controller/lists/OpeningTypesController.ts
src/main/app/feature-flags/LaunchDarklyClient.ts

fixing master branch sonarcloud issues
```
[ ] Yes
[ ] No
```

sonarcloud fixes

---

src/main/app/feature-flags/LaunchDarklyClient.ts

launchdarkly fixes for sonarcloud
```
[ ] Yes
[x] No
```

added ld fix for sonarcloud

---

src/main/app/feature-flags/LaunchDarklyClient.ts

attempt another fix for sonarcloud issues
```
[ ] Yes
[x] No
```

sonarcloud fix 2

---

sonar-project.properties
src/main/app/feature-flags/LaunchDarklyClient.ts

returning code to original 
ignoring the sonarcloud issue
```
[ ] Yes
[x] No
```

sonarcloud ignore launchdarkly

---

package.json
src/test/functional/features/admin/general-info.feature
src/test/functional/features/super_admin/additional-links.feature
src/test/functional/features/super_admin/admin-court-addresses.feature
src/test/functional/features/viewer/viewer-login.feature
src/test/functional/steps/court-addresses.ts
src/test/functional/steps/courts.ts
yarn.lock

trying to check users login

---

src/main/utils/error.ts
src/test/functional/features/admin/admin-login.feature

https://tools.hmcts.net/jira/browse/FACT-1408
changed error message see ticket.
```
[ ] Yes
[x] No
```

FACT-1408 changed no roles error message

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/FACT-1414
upgrading redis 4 to 6
```
[ ] Yes
[x] No
```

FACT-1414 Update Redis cache from 4 to 6

---

package.json
src/main/app/controller/courts/AddressController.ts
src/main/types/Abbreviation.ts
src/main/utils/AddressUtils.ts
src/test/functional/features/super_admin/admin-court-addresses.feature
src/test/unit/app/controller/courts/AddressController.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-1260
```
[ ] Yes
[x] No
```

extra validation for court addresses

---

src/test/functional/steps/logout.ts

increasing time for logout link

---

package.json
src/main/app/controller/courts/AddressController.ts
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-1454
```
[ ] Yes
[x] No
```

Uppercase and Lowercase postcodes check

---

src/main/modules/helmet/index.ts

https://tools.hmcts.net/jira/browse/FACT-1461
Added dynatrace to allow list.
```
[ ] Yes
[x] No
```

FACT-1461 Added dynatrace to allow list

---

src/main/assets/js/tinymce.config.ts
src/main/assets/js/utilities.ts

https://tools.hmcts.net/jira/browse/FACT-1636
update tinymce to add link to open on new tab by default
```
[ ] Yes
[x] No
```

update tinymce to add link to open on new tab by default

---

README.md

https://tools.hmcts.net/jira/browse/FACT-1677
Update readme
```
[ ] Yes
[x] No
```

FACT-1677 update readme

---

Jenkinsfile_CNP
Jenkinsfile_nightly
docker/database/Dockerfile

https://tools.hmcts.net/jira/browse/FACT-1881
Docker limit fix
```
[ ] Yes
[x] No
```

Docker limit fix

---

src/main/app/controller/courts/EditCourtController.ts
src/test/unit/app/controller/courts/EditCourtController.ts

[FACT-1984](https://tools.hmcts.net/jira/browse/FACT-1984)
- Changes how viewer role interacts with court locking now a viewer role: 
- Doesn't add or create court lock
- Is not blocked by court lock 
- Adds unit test for these scenarios
```
[ ] Yes
[x] No
```

FACT-1984 - adds check for viewer role before adding a court lock

---

package.json

We run tests twice for no reason on this repo. 
This ticket fixes that in line with other teams.

Remove duplicate test runs on yarn test & yarn test:coverage

---

charts/fact-admin/Chart.yaml

remove idam-pr entirely

---

README.md

Update README.md to trigger new master build

---

.github/renovate.json
package.json
yarn.lock

https://tools.hmcts.net/jira/browse/FACT-2522
Downgrade tinyMCE to latest V7
Set Renovate to not update to V8
```
[ ] Yes
[x] No
```

FACT-2522 Downgrade tinyMCE and update Renovate config
